// src/components/Goals.tsx
import React, { useState } from 'react';
import { 
  Target, Plus, Trash2, Edit2, X, CheckCircle2, Clock, TrendingUp, PiggyBank,
  Home, Car, Plane, Smartphone, GraduationCap, HeartPulse, ShoppingBag, Gamepad2, Camera, Globe, Briefcase, Coffee,
  Calendar as CalendarIcon, ChevronLeft, ChevronRight, ArrowUpRight
} from 'lucide-react';
import { Goal } from '../types';
import { formatCurrency, cn } from '../lib/utils';
import { format, differenceInDays, parseISO } from 'date-fns';
import { id as localeId } from 'date-fns/locale';
import DatePicker from './UI/DatePicker';


interface GoalsProps {
  goals: Goal[];
  onAdd: (goal: Omit<Goal, 'id'>) => void;
  onUpdate: (goal: Goal) => void;
  onDelete: (id: string) => void;
  onAddSavings: (goalId: string, amount: number) => void;
  userId: string;
}

const GOAL_ICONS = [
  { id: 'home', icon: Home },
  { id: 'car', icon: Car },
  { id: 'plane', icon: Plane },
  { id: 'phone', icon: Smartphone },
  { id: 'edu', icon: GraduationCap },
  { id: 'health', icon: HeartPulse },
  { id: 'shop', icon: ShoppingBag },
  { id: 'game', icon: Gamepad2 },
  { id: 'camera', icon: Camera },
  { id: 'world', icon: Globe },
  { id: 'work', icon: Briefcase },
  { id: 'coffee', icon: Coffee },
];

export default function Goals({ goals = [], onAdd, onUpdate, onDelete, onAddSavings, userId }: GoalsProps) {
  const [showModal, setShowModal] = useState(false);
  const [showSavingsModal, setShowSavingsModal] = useState<Goal | null>(null);
  const [editGoal, setEditGoal] = useState<Goal | null>(null);
  const [savingsAmount, setSavingsAmount] = useState('');

  const [form, setForm] = useState({
    name: '', targetAmount: '', savedAmount: '0', deadline: '', icon: 'home', color: '#8b5cf6',
  });

  const getIconById = (id: string) => {
    return GOAL_ICONS.find(i => i.id === id)?.icon || Target;
  };

  const openAdd = () => {
    setEditGoal(null);
    setForm({ name: '', targetAmount: '', savedAmount: '0', deadline: '', icon: 'home', color: '#8b5cf6' });
    setShowModal(true);
  };

  const openEdit = (g: Goal) => {
    setEditGoal(g);
    setForm({
      name: g.name,
      targetAmount: String(g.targetAmount),
      savedAmount: String(g.savedAmount),
      deadline: g.deadline || '',
      icon: g.icon,
      color: g.color,
    });
    setShowModal(true);
  };

  const handleSubmit = () => {
    if (!form.name || !form.targetAmount) return;
    const payload = {
      userId,
      name: form.name,
      targetAmount: Number(form.targetAmount),
      savedAmount: Number(form.savedAmount) || 0,
      deadline: form.deadline || undefined,
      icon: form.icon,
      color: form.color,
    };
    if (editGoal) {
      onUpdate({ ...editGoal, ...payload });
    } else {
      onAdd(payload);
    }
    setShowModal(false);
  };

  const handleAddSavings = () => {
    if (!showSavingsModal || !savingsAmount) return;
    onAddSavings(showSavingsModal.id, Number(savingsAmount));
    setSavingsAmount('');
    setShowSavingsModal(null);
  };

  const totalTarget = (goals || []).reduce((s, g) => s + g.targetAmount, 0);
  const totalSaved = (goals || []).reduce((s, g) => s + g.savedAmount, 0);
  const completedGoals = (goals || []).filter(g => g.savedAmount >= g.targetAmount).length;

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div className="group lg:hidden">
          <h2 className="text-2xl font-bold text-text-primary tracking-tight">Tujuan</h2>
          <p className="text-[10px] sm:text-[11px] text-text-secondary font-medium mt-1 uppercase tracking-widest">Target & Progres Tabungan</p>
          <div className="h-1 w-12 bg-linear-to-r from-accent to-secondary rounded-full mt-3 opacity-80 group-hover:w-20 transition-all duration-500" />
        </div>
        <button
          onClick={openAdd}
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-4 py-2.5 bg-gradient-to-r from-accent to-secondary text-white rounded-2xl text-xs font-black shadow-lg shadow-accent/20 hover:shadow-accent/40 hover:scale-[1.02] active:scale-[0.98] transition-all"
        >
          <Plus className="w-4 h-4" />
          Tambah Tujuan
        </button>
      </div>

      {/* Summary Cards */}
      {goals && goals.length > 0 && (
        <div className="flex overflow-x-auto sm:grid sm:grid-cols-3 gap-3 sm:gap-4 no-scrollbar -mx-4 px-4 sm:mx-0 sm:px-0 pb-2 sm:pb-0">
          {[
            { label: 'Total Target', value: formatCurrency(totalTarget), icon: <Target className="w-3.5 h-3.5" />, color: 'text-accent', bg: 'bg-accent/5' },
            { label: 'Total Terkumpul', value: formatCurrency(totalSaved), icon: <PiggyBank className="w-3.5 h-3.5" />, color: 'text-success', bg: 'bg-success/5' },
            { label: 'Tujuan Tercapai', value: `${completedGoals} / ${goals.length}`, icon: <CheckCircle2 className="w-3.5 h-3.5" />, color: 'text-emerald-500', bg: 'bg-emerald-500/5' },

          ].map((s, i) => (
            <div key={i} className="flex-shrink-0 w-[150px] sm:w-auto bg-card-bg p-3.5 rounded-2xl border border-border-ui shadow-sm">
              <div className="flex items-center gap-2 mb-2">
                <div className={cn("p-1.5 rounded-lg", s.bg)}>
                  <span className={s.color}>{s.icon}</span>
                </div>
                <p className="text-[8px] font-medium text-text-secondary uppercase tracking-widest truncate">{s.label}</p>
              </div>
              <div className="flex items-center gap-1">
                {s.label === 'Total Terkumpul' && <ArrowUpRight className="w-3 h-3 text-success" />}
                <p className={cn("text-sm sm:text-base font-bold tracking-tight currency-font", s.color)}>{s.value}</p>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Goals Grid */}
      {!goals || goals.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-24 gap-4">
          <div className="w-16 h-16 rounded-3xl bg-accent/10 flex items-center justify-center text-3xl">🎯</div>
          <p className="text-sm font-bold text-text-secondary">Belum ada tujuan tabungan</p>
          <button onClick={openAdd} className="px-4 py-2 bg-accent/10 text-accent rounded-xl text-xs font-black hover:bg-accent/20 transition-colors">
            Buat Tujuan Pertama
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {goals.map((goal, i) => {
              const pct = Math.min((goal.savedAmount / goal.targetAmount) * 100, 100);
              const remaining = goal.targetAmount - goal.savedAmount;
              const isComplete = pct >= 100;
              const daysLeft = goal.deadline ? differenceInDays(new Date(goal.deadline), new Date()) : null;

              return (
                <div
                  key={goal.id}
                  className="bg-card-bg rounded-3xl border border-border-ui overflow-hidden shadow-sm hover:shadow-md hover:border-accent/30 transition-all"
                >
                  {/* Card Header */}
                  <div className="p-4 sm:p-5 relative" style={{ background: `linear-gradient(135deg, ${goal.color}, ${goal.color}dd)` }}>
                    <div className="flex justify-between items-start">
                      <div className="w-10 h-10 bg-white/20 backdrop-blur-md rounded-xl flex items-center justify-center text-white">
                        {React.createElement(getIconById(goal.icon), { className: "w-6 h-6" })}
                      </div>
                      <div className="flex gap-1">
                        <button onClick={() => openEdit(goal)} className="p-2.5 bg-white/20 hover:bg-white/30 rounded-xl transition-colors">
                          <Edit2 className="w-4 h-4 text-white" />
                        </button>
                        <button onClick={() => onDelete(goal.id)} className="p-2.5 bg-white/20 hover:bg-red-500/50 rounded-xl transition-colors">
                          <Trash2 className="w-4 h-4 text-white" />
                        </button>
                      </div>
                    </div>
                    <h3 className="text-base font-bold text-white mt-3 leading-tight">{goal.name}</h3>
                    {isComplete && (
                      <div className="flex items-center gap-1 mt-1">
                        <CheckCircle2 className="w-3.5 h-3.5 text-white" />
                        <span className="text-[10px] font-bold text-white uppercase tracking-wide">Tercapai!</span>
                      </div>
                    )}
                  </div>

                  {/* Card Body */}
                  <div className="p-3.5 sm:p-4 space-y-3">
                    {/* Progress */}
                    <div>
                      <div className="flex justify-between items-center mb-1.5">
                        <span className="text-[10px] font-medium text-text-secondary">Progress</span>
                        <span className="text-[10px] font-bold currency-font" style={{ color: goal.color }}>
                          {pct > 0 && pct < 1 ? '< 1' : Math.round(pct)}%
                        </span>

                      </div>
                      <div className="h-2 bg-bg-main rounded-full overflow-hidden">
                        <div
                          className="h-full rounded-full"
                          style={{ backgroundColor: goal.color, width: `${pct}%` }}
                        />
                      </div>
                    </div>

                    {/* Amounts */}
                    <div className="flex justify-between">
                      <div>
                        <p className="text-[9px] text-text-secondary uppercase tracking-widest font-medium">Terkumpul</p>
                        <div className="flex items-center gap-1">
                          <ArrowUpRight className="w-3 h-3 text-success" />
                          <p className="text-sm font-bold text-success currency-font">{formatCurrency(goal.savedAmount)}</p>
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="text-[9px] text-text-secondary uppercase tracking-widest font-medium">Target</p>
                        <p className="text-sm font-bold text-text-primary currency-font">{formatCurrency(goal.targetAmount)}</p>
                      </div>
                    </div>

                    {/* Remaining + Deadline */}
                    <div className="flex items-center justify-between text-[9px]">
                      {remaining > 0 ? (
                        <span className="text-text-secondary">Sisa Target: <span className="font-bold text-warning currency-font">{formatCurrency(remaining)}</span></span>

                      ) : (
                        <span className="text-success font-bold">✅ Sudah tercapai!</span>
                      )}
                      {daysLeft !== null && (
                        <span className={cn("flex items-center gap-1 font-bold", daysLeft < 30 ? 'text-danger' : 'text-text-secondary')}>
                          <Clock className="w-2.5 h-2.5" />
                          {daysLeft > 0 ? `${daysLeft} hari lagi` : 'Kedaluwarsa'}
                        </span>
                      )}
                    </div>

                    {/* Add Savings Button */}
                    {!isComplete && (
                      <button
                        onClick={() => setShowSavingsModal(goal)}
                        className="w-full py-3 bg-linear-to-r from-accent to-secondary text-white rounded-xl text-[10px] font-black shadow-lg shadow-accent/20 hover:scale-[1.02] active:scale-[0.98] transition-all"
                      >
                        + TAMBAH TABUNGAN
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
        </div>
      )}
           {/* Add/Edit Goal Modal */}
      {showModal && (
        <div className="fixed inset-0 z-50 flex items-start sm:items-center justify-center p-4 overflow-y-auto">
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setShowModal(false)} />
          <div className="relative bg-card-bg rounded-3xl border border-border-ui shadow-2xl w-full max-w-md p-6 mt-4 sm:mt-0">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-black text-text-primary">{editGoal ? 'Edit Tujuan' : 'Tambah Tujuan'}</h3>
              <button onClick={() => setShowModal(false)} className="p-2 hover:bg-bg-main rounded-lg transition-colors">
                <X className="w-4 h-4 text-text-secondary" />
              </button>
            </div>

            <div className="space-y-4">
              {/* Icon Picker */}
              <div>
                <label className="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-2 block">Ikon Tujuan</label>
                <div className="grid grid-cols-6 gap-2">
                  {GOAL_ICONS.map(i => (
                    <button 
                      key={i.id} 
                      onClick={() => setForm(f => ({ ...f, icon: i.id }))} 
                      className={cn(
                        "w-10 h-10 rounded-xl flex items-center justify-center transition-all", 
                        form.icon === i.id ? 'bg-accent/20 scale-110 ring-2 ring-accent text-accent' : 'bg-bg-main text-text-secondary hover:bg-border-ui hover:text-text-primary'
                      )}
                    >
                      <i.icon className="w-5 h-5" />
                    </button>
                  ))}
                </div>
              </div>

              {/* Color Picker */}
              <div>
                <label className="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-2 block">Pilih Warna</label>
                <div className="flex items-center gap-3">
                  <div className="flex flex-wrap gap-2 flex-1">
                    {['#8b5cf6', '#f43f5e', '#f59e0b', '#10b981', '#0ea5e9', '#d946ef'].map(c => (
                      <button 
                        key={c} 
                        onClick={() => setForm(f => ({ ...f, color: c }))} 
                        className={cn("w-8 h-8 rounded-full transition-all hover:scale-110", form.color === c && 'ring-2 ring-offset-2 ring-accent ring-offset-card-bg scale-110')}
                        style={{ backgroundColor: c }}
                      />
                    ))}
                  </div>
                  <div className="relative group">
                    <input 
                      type="color" 
                      value={form.color} 
                      onChange={e => setForm(f => ({ ...f, color: e.target.value }))}
                      className="w-10 h-10 rounded-xl bg-bg-main border border-border-ui p-1 cursor-pointer"
                    />
                  </div>
                </div>
              </div>

              <div>
                <label className="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-1 block">Nama Tujuan</label>
                <input type="text" value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} placeholder="Contoh: Tabungan Rumah" className="w-full p-3 bg-bg-main rounded-xl border border-border-ui focus:border-accent outline-none text-sm font-bold text-text-primary transition-all" />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-1 block">Target (Rp)</label>
                  <input type="number" value={form.targetAmount} onChange={e => setForm(f => ({ ...f, targetAmount: e.target.value }))} placeholder="500000000" className="w-full p-3 bg-bg-main rounded-xl border border-border-ui focus:border-accent outline-none text-sm font-bold text-text-primary transition-all" />
                </div>
                <div>
                  <label className="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-1 block">Sudah Terkumpul</label>
                  <input type="number" value={form.savedAmount} onChange={e => setForm(f => ({ ...f, savedAmount: e.target.value }))} placeholder="0" className="w-full p-3 bg-bg-main rounded-xl border border-border-ui focus:border-accent outline-none text-sm font-bold text-text-primary transition-all" />
                </div>
              </div>

              <div>
                <label className="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-1 block">Target Tanggal (Opsional)</label>
                <DatePicker value={form.deadline} onChange={v => setForm(f => ({ ...f, deadline: v }))} dropUp placeholder="dd/mm/yyyy" />
              </div>

              <button onClick={handleSubmit} disabled={!form.name || !form.targetAmount} className="w-full py-3 bg-gradient-to-r from-accent to-secondary text-white rounded-2xl font-black text-sm shadow-lg shadow-accent/20 hover:scale-[1.02] active:scale-[0.98] transition-all disabled:opacity-50 disabled:scale-100">
                {editGoal ? 'Simpan Perubahan' : 'Tambah Tujuan'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Add Savings Modal */}
      {showSavingsModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setShowSavingsModal(null)} />
          <div className="relative bg-card-bg rounded-3xl border border-border-ui shadow-2xl w-full max-w-sm p-6">
            <div className="flex justify-between items-center mb-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl flex items-center justify-center text-white shadow-lg" style={{ backgroundColor: showSavingsModal.color }}>
                  {React.createElement(getIconById(showSavingsModal.icon), { className: "w-5 h-5" })}
                </div>
                <div>
                  <h3 className="text-sm font-black text-text-primary">{showSavingsModal.name}</h3>
                  <p className="text-[10px] text-text-secondary">Tambah jumlah tabungan</p>
                </div>
              </div>
              <button onClick={() => setShowSavingsModal(null)} className="p-2 hover:bg-bg-main rounded-lg transition-colors">
                <X className="w-4 h-4 text-text-secondary" />
              </button>
            </div>
            <div className="space-y-4">
              <input type="number" value={savingsAmount} onChange={e => setSavingsAmount(e.target.value)} placeholder="Masukkan jumlah (Rp)" className="w-full p-3 bg-bg-main rounded-xl border border-border-ui focus:border-accent outline-none text-sm font-bold text-text-primary transition-all" autoFocus />
              <button onClick={handleAddSavings} disabled={!savingsAmount || Number(savingsAmount) <= 0} className="w-full py-3 bg-gradient-to-r from-accent to-secondary text-white rounded-2xl font-black text-sm shadow-lg shadow-accent/20 hover:scale-[1.02] transition-all disabled:opacity-50">
                Tambah {savingsAmount ? formatCurrency(Number(savingsAmount)) : ''}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// src/components/Goals.vue
<template>
  <div class="space-y-6 max-w-7xl mx-auto">
    <!-- Header (Mobile only) -->
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 lg:hidden mb-4">
      <button
        @click="openAdd"
        class="w-full flex items-center justify-center gap-2 py-3 bg-gradient-to-r from-accent to-secondary text-white rounded-xl text-xs font-black shadow-lg shadow-accent/20 hover:scale-[1.02] active:scale-[0.98] transition-all"
      >
        <Plus class="w-4 h-4" /> TAMBAH TUJUAN BARU
      </button>
    </div>

    <!-- Summary Cards -->
    <div v-if="goals && goals.length > 0" class="grid grid-cols-2 sm:grid-cols-3 gap-3 sm:gap-4 pb-3 sm:pb-0">
      <div v-for="(s, i) in summaryData" :key="i" :class="['p-2 flex flex-col justify-between', i === 2 ? 'col-span-2 sm:col-span-1' : '']">
        <div class="flex items-center gap-2 mb-1">
          <span :class="s.color"><component :is="s.icon" class="w-3.5 h-3.5" /></span>
          <p class="text-[9px] font-black text-text-secondary uppercase tracking-[0.15em] truncate">{{ s.label }}</p>
        </div>
        <div class="flex items-center gap-1.5">
          <ArrowUpRight v-slot:arrow v-if="s.label === 'Total Terkumpul'" class="w-3.5 h-3.5 text-success" />
          <p :class="['text-base sm:text-lg font-black tracking-tight currency-font', s.color]">{{ s.value }}</p>
        </div>
      </div>
    </div>

    <!-- Goals Grid -->
    <div v-if="!goals || goals.length === 0" class="flex flex-col items-center justify-center py-24 gap-4">
      <div class="w-20 h-20 rounded-lg bg-accent/10 flex items-center justify-center text-4xl shadow-inner">🎯</div>
      <p class="text-sm font-bold text-text-secondary">Belum ada tujuan tabungan</p>
      <button @click="openAdd" class="px-6 py-3 bg-accent text-white rounded-lg text-xs font-black shadow-lg shadow-accent/20 hover:scale-[1.02] active:scale-[0.98] transition-all">
        + Buat Tujuan Pertama
      </button>
    </div>
    <div v-else class="space-y-1">
      <div
        v-for="goal in goals"
        :key="goal.id"
        class="py-5 border-b border-border-ui/35 transition-all group"
      >
        <div class="flex items-start justify-between gap-4">
          <div class="flex items-center gap-3.5 min-w-0 flex-1">
            <div class="w-11 h-11 rounded-xl flex items-center justify-center text-white shrink-0 shadow-inner" :style="{ backgroundColor: goal.color || '#2D4DB5' }">
              <component :is="getIconById(goal.icon)" class="w-5.5 h-5.5" />
            </div>
            <div class="min-w-0 flex-1">
              <div class="flex items-center gap-2">
                <h3 class="text-sm font-bold text-text-primary truncate leading-tight">{{ goal.name }}</h3>
                <span v-if="isComplete(goal)" class="text-[9px] font-black text-success uppercase tracking-wider bg-success/10 px-2 py-0.5 rounded-full">Tercapai</span>
              </div>
              
              <!-- Amounts & deadline -->
              <div class="flex items-center gap-2.5 text-[10px] text-text-secondary mt-1">
                <span class="currency-font font-bold text-text-primary">{{ formatCurrency(goal.savedAmount) }}</span>
                <span>/</span>
                <span class="currency-font">{{ formatCurrency(goal.targetAmount) }}</span>
                <span v-if="getDaysLeft(goal) !== null" class="opacity-60">•</span>
                <span v-if="getDaysLeft(goal) !== null" class="opacity-70">{{ getDaysLeft(goal)! > 0 ? `${getDaysLeft(goal)} hari lagi` : 'Kedaluwarsa' }}</span>
              </div>
            </div>
          </div>

          <!-- Action buttons (Edit & Delete) -->
          <div class="flex gap-1">
            <button @click="openEdit(goal)" class="p-2 text-text-secondary hover:text-accent rounded-lg transition-colors">
              <Edit2 class="w-4 h-4" />
            </button>
            <button @click="$emit('delete', goal.id)" class="p-2 text-text-secondary hover:text-danger rounded-lg transition-colors">
              <Trash2 class="w-4 h-4" />
            </button>
          </div>
        </div>

        <!-- Progress bar under the details -->
        <div class="mt-3.5">
          <div class="flex justify-between items-center mb-1 text-[9px] text-text-secondary/70">
            <span>Progress</span>
            <span class="font-bold currency-font">{{ getGoalPercentage(goal) }}%</span>
          </div>
          <div class="h-1.5 bg-bg-main rounded-full overflow-hidden">
            <div
              class="h-full rounded-full transition-all duration-500"
              :style="{ backgroundColor: goal.color, width: `${Math.min((goal.savedAmount / goal.targetAmount) * 100, 100)}%` }"
            />
          </div>
        </div>

        <!-- Sisa target + Tambah Tabungan Button -->
        <div class="mt-4 flex items-center justify-between gap-4">
          <span class="text-[9px] text-text-secondary">
            Sisa Target: <span class="font-bold text-warning currency-font">{{ formatCurrency(getRemaining(goal)) }}</span>
          </span>
          <button
            v-if="!isComplete(goal)"
            @click="showSavingsModal = goal"
            class="px-4 py-2 bg-accent/8 border border-accent/15 text-accent rounded-full text-[10px] font-black active:scale-95 transition-all"
          >
            + Tabungan
          </button>
        </div>
      </div>
    </div>

    <!-- Add/Edit Goal Modal -->
    <Teleport to="body">
      <div v-if="showModal" class="fixed inset-0 z-50 flex sm:p-4 overflow-y-auto items-center justify-center">
        <div @click="showModal = false" class="fixed inset-0 bg-black/60 backdrop-blur-sm" />
        <div class="relative bg-bg-main sm:rounded-2xl shadow-lg w-full sm:max-w-md p-6 z-10 my-auto border-0">
          <div class="flex justify-between items-center mb-6">
            <h3 class="text-lg font-black text-text-primary">{{ editGoal ? 'Edit Tujuan' : 'Tambah Tujuan' }}</h3>
            <button @click="showModal = false" class="p-2 hover:bg-bg-main rounded-lg transition-colors">
              <X class="w-4 h-4 text-text-secondary" />
            </button>
          </div>

          <div class="space-y-4">
            <!-- Icon Picker -->
            <div>
              <label class="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-2 block">Ikon Tujuan</label>
              <div class="grid grid-cols-6 gap-2">
                <button 
                  v-for="i in GOAL_ICONS" 
                  :key="i.id" 
                  @click="form.icon = i.id" 
                  :class="[
                    'w-10 h-10 rounded-lg flex items-center justify-center transition-all', 
                    form.icon === i.id ? 'bg-accent/20 scale-110 ring-2 ring-accent text-accent' : 'bg-bg-main text-text-secondary hover:bg-border-ui hover:text-text-primary'
                  ]"
                >
                  <component :is="i.icon" class="w-5 h-5" />
                </button>
              </div>
            </div>

            <!-- Color Picker -->
            <div>
              <label class="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-2 block">Pilih Warna</label>
              <div class="flex items-center gap-3">
                <div class="flex flex-wrap gap-2 flex-1">
                  <button 
                    v-for="c in ['#8b5cf6', '#f43f5e', '#f59e0b', '#10b981', '#0ea5e9', '#d946ef']" 
                    :key="c" 
                    @click="form.color = c" 
                    :class="['w-8 h-8 rounded-full transition-all hover:scale-110', form.color === c && 'ring-2 ring-offset-2 ring-accent ring-offset-card-bg scale-110']"
                    :style="{ backgroundColor: c }"
                  />
                </div>
                <input 
                  type="color" 
                  v-model="form.color"
                  class="w-10 h-10 rounded-lg bg-bg-main border border-border-ui p-1 cursor-pointer"
                />
              </div>
            </div>

            <div>
              <label class="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-1 block">Nama Tujuan</label>
              <input type="text" v-model="form.name" placeholder="Contoh: Tabungan Rumah" class="w-full p-3 bg-bg-main rounded-lg border border-border-ui focus:border-accent outline-none text-sm font-bold text-text-primary transition-all" />
            </div>

            <div class="grid grid-cols-2 gap-3">
              <div>
                <label class="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-1 block">Target (Rp)</label>
                <input type="text" v-model="form.targetAmount" @input="form.targetAmount = formatInputNumber(form.targetAmount)" placeholder="500.000.000" class="w-full p-3 bg-bg-main rounded-lg border border-border-ui focus:border-accent outline-none text-sm font-bold text-text-primary transition-all" />
              </div>
              <div>
                <label class="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-1 block">Sudah Terkumpul</label>
                <input type="text" v-model="form.savedAmount" @input="form.savedAmount = formatInputNumber(form.savedAmount)" placeholder="0" class="w-full p-3 bg-bg-main rounded-lg border border-border-ui focus:border-accent outline-none text-sm font-bold text-text-primary transition-all" />
              </div>
            </div>

            <div>
              <label class="text-[10px] font-black text-text-secondary uppercase tracking-widest mb-1 block">Target Tanggal (Opsional)</label>
              <DatePicker :value="form.deadline" @change="form.deadline = $event" dropUp placeholder="dd/mm/yyyy" />
            </div>

            <button @click="handleSubmit" :disabled="!form.name || !form.targetAmount" class="w-full py-3 bg-gradient-to-r from-accent to-secondary text-white rounded-lg font-black text-sm shadow-lg shadow-accent/20 hover:scale-[1.02] active:scale-[0.98] transition-all disabled:opacity-50 disabled:scale-100">
              {{ editGoal ? 'Simpan Perubahan' : 'Tambah Tujuan' }}
            </button>
          </div>
        </div>
      </div>
    </Teleport>

    <!-- Add Savings Modal -->
    <Teleport to="body">
      <div v-if="showSavingsModal" class="fixed inset-0 z-50 flex sm:p-4 overflow-y-auto items-center justify-center">
        <div @click="showSavingsModal = null" class="fixed inset-0 bg-black/60 backdrop-blur-sm" />
        <div class="relative bg-bg-main sm:rounded-2xl shadow-lg w-full sm:max-w-sm p-6 z-10 my-auto border-0">
          <div class="flex justify-between items-center mb-4">
            <div class="flex items-center gap-3">
              <div class="w-10 h-10 rounded-lg flex items-center justify-center text-white shadow-lg" :style="{ backgroundColor: showSavingsModal.color }">
                <component :is="getIconById(showSavingsModal.icon)" class="w-5 h-5" />
              </div>
              <div>
                <h3 class="text-sm font-black text-text-primary">{{ showSavingsModal.name }}</h3>
                <p class="text-[10px] text-text-secondary">Tambah jumlah tabungan</p>
              </div>
            </div>
            <button @click="showSavingsModal = null" class="p-2 hover:bg-bg-main rounded-lg transition-colors">
              <X class="w-4 h-4 text-text-secondary" />
            </button>
          </div>
          <div class="space-y-4">
            <input type="text" v-model="savingsAmount" @input="savingsAmount = formatInputNumber(savingsAmount)" placeholder="Masukkan jumlah (Rp)" class="w-full p-3 bg-bg-main rounded-lg border border-border-ui focus:border-accent outline-none text-sm font-bold text-text-primary transition-all" autofocus />
            <button @click="handleAddSavings" :disabled="!savingsAmount || Number(parseInputNumber(savingsAmount)) <= 0" class="w-full py-3 bg-gradient-to-r from-accent to-secondary text-white rounded-lg font-black text-sm shadow-lg shadow-accent/20 hover:scale-[1.02] transition-all disabled:opacity-50">
              Tambah {{ savingsAmount ? formatCurrency(Number(parseInputNumber(savingsAmount))) : '' }}
            </button>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { 
  Target, Plus, Trash2, Edit2, X, CheckCircle2, PiggyBank,
  Home, Car, Plane, Smartphone, GraduationCap, HeartPulse, ShoppingBag, Gamepad2, Camera, Globe, Briefcase, Coffee,
  ArrowUpRight
} from '@lucide/vue';
import type { Goal } from '../types';
import { formatCurrency, formatInputNumber, parseInputNumber } from '../lib/utils';
import { differenceInDays } from 'date-fns';
import DatePicker from './UI/DatePicker.vue';

interface Props {
  goals: Goal[];
  userId: string;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  add: [goal: Omit<Goal, 'id'>];
  update: [goal: Goal];
  delete: [id: string];
  addSavings: [goalId: string, amount: number];
}>();

const showModal = ref(false);
const showSavingsModal = ref<Goal | null>(null);
const editGoal = ref<Goal | null>(null);
const savingsAmount = ref('');

const form = ref({
  name: '', targetAmount: '', savedAmount: '0', deadline: '', icon: 'home', color: '#8b5cf6',
});

const GOAL_ICONS = [
  { id: 'home', icon: Home },
  { id: 'car', icon: Car },
  { id: 'plane', icon: Plane },
  { id: 'phone', icon: Smartphone },
  { id: 'edu', icon: GraduationCap },
  { id: 'health', icon: HeartPulse },
  { id: 'shop', icon: ShoppingBag },
  { id: 'game', icon: Gamepad2 },
  { id: 'camera', icon: Camera },
  { id: 'world', icon: Globe },
  { id: 'work', icon: Briefcase },
  { id: 'coffee', icon: Coffee },
];

const getIconById = (id: string) => {
  return GOAL_ICONS.find(i => i.id === id)?.icon || Target;
};

const openAdd = () => {
  editGoal.value = null;
  form.value = { name: '', targetAmount: '', savedAmount: '0', deadline: '', icon: 'home', color: '#8b5cf6' };
  showModal.value = true;
};

const openEdit = (g: Goal) => {
  editGoal.value = g;
  form.value = {
    name: g.name,
    targetAmount: formatInputNumber(String(g.targetAmount)),
    savedAmount: formatInputNumber(String(g.savedAmount)),
    deadline: g.deadline || '',
    icon: g.icon,
    color: g.color,
  };
  showModal.value = true;
};

const handleSubmit = () => {
  if (!form.value.name || !form.value.targetAmount) return;
  const payload = {
    userId: props.userId,
    name: form.value.name,
    targetAmount: Number(parseInputNumber(form.value.targetAmount)),
    savedAmount: Number(parseInputNumber(form.value.savedAmount)) || 0,
    deadline: form.value.deadline || undefined,
    icon: form.value.icon,
    color: form.value.color,
  };
  if (editGoal.value) {
    emit('update', { ...editGoal.value, ...payload });
  } else {
    emit('add', payload);
  }
  showModal.value = false;
};

const handleAddSavings = () => {
  if (!showSavingsModal.value || !savingsAmount.value) return;
  emit('addSavings', showSavingsModal.value.id, Number(parseInputNumber(savingsAmount.value)));
  savingsAmount.value = '';
  showSavingsModal.value = null;
};

const totalTarget = computed(() => (props.goals || []).reduce((s, g) => s + g.targetAmount, 0));
const totalSaved = computed(() => (props.goals || []).reduce((s, g) => s + g.savedAmount, 0));
const completedGoals = computed(() => (props.goals || []).filter(g => g.savedAmount >= g.targetAmount).length);

const summaryData = computed(() => [
  { label: 'Total Target', value: formatCurrency(totalTarget.value), icon: Target, color: 'text-accent', bg: 'bg-accent/10' },
  { label: 'Total Terkumpul', value: formatCurrency(totalSaved.value), icon: PiggyBank, color: 'text-success', bg: 'bg-success/10' },
  { label: 'Tujuan Tercapai', value: `${completedGoals.value} / ${props.goals.length}`, icon: CheckCircle2, color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
]);

const getGoalPercentage = (goal: Goal) => {
  const pct = (goal.savedAmount / goal.targetAmount) * 100;
  return pct > 0 && pct < 1 ? '< 1' : Math.round(pct);
};

const getRemaining = (goal: Goal) => goal.targetAmount - goal.savedAmount;

const isComplete = (goal: Goal) => (goal.savedAmount / goal.targetAmount) * 100 >= 100;

const getDaysLeft = (goal: Goal) => {
  return goal.deadline ? differenceInDays(new Date(goal.deadline), new Date()) : null;
};
</script>
