// src/components/Layout.tsx
import React, { useState, useEffect, useMemo, useTransition } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Home, List, PieChart, Target, User, LogOut, Moon, Sun, Plus, RefreshCw, TrendingUp, Wallet, StickyNote, Flag, Cloud, CloudOff, LayoutGrid, X } from 'lucide-react';

import { cn, formatCurrency } from '../lib/utils';
import { Transaction, Budget, User as UserType } from '../types';
import { isToday } from 'date-fns';

interface LayoutProps {
  children: React.ReactNode;
  activeTab: string;
  setActiveTab: (tab: string) => void;
  user: UserType;
  isDark: boolean;
  toggleTheme: () => void;
  transactions: Transaction[];
  budgets: Budget[];
  syncing: boolean;
  syncStatus?: string;
  onAddClick: () => void;
  onLogout: () => void;
  wallpaper?: string;
}

export default function Layout({
  children, activeTab, setActiveTab, user, isDark, toggleTheme, transactions, budgets, syncing, syncStatus, onAddClick, onLogout, wallpaper = 'none'
}: LayoutProps) {
  const [isOnline, setIsOnline] = useState(navigator.onLine);
  const [isPending, startTransition] = useTransition();
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(() => typeof window !== 'undefined' ? window.innerWidth < 1024 : false);


  useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 1024);
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  const handleTabClick = (tabId: string) => {
    if (activeTab === tabId) return;
    startTransition(() => {
      setActiveTab(tabId);
    });
  };


  useEffect(() => {
    const handleOnline = () => setIsOnline(true);
    const handleOffline = () => setIsOnline(false);
    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);
    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, []);

  const mainTabs = [
    { id: 'home', icon: Home, label: 'Dashboard' },
    { id: 'transactions', icon: List, label: 'Pencatatan' },
    { id: 'budgets', icon: Target, label: 'Budgeting' },
    { id: 'reports', icon: PieChart, label: 'Laporan' },
    { id: 'goals', icon: Flag, label: 'Goals' },
    { id: 'notes', icon: StickyNote, label: 'Catatan' },
  ];

  const allTabs = [...mainTabs, { id: 'profile', icon: User, label: 'Akun' }];

  // Live stats for sidebar badges
  const sidebarStats = useMemo(() => {
    const todayTxCount = (transactions || []).filter(t => isToday(new Date(t.date))).length;
    return { todayTxCount };
  }, [transactions]);

  const transactionBadge = sidebarStats.todayTxCount > 0 ? sidebarStats.todayTxCount : null;

  const activeTabDef = allTabs.find(t => t.id === activeTab);

  return (
    <div className="h-screen bg-bg-main flex overflow-hidden relative">

      {/* Sidebar for Desktop */}
      <aside className="hidden lg:flex w-64 bg-sidebar-bg flex-col sticky top-0 h-screen border-r border-sidebar-border transition-colors overflow-hidden z-40">
        <div className="px-6 py-6 border-b border-sidebar-border/30 flex items-center gap-3">
          <button
            onClick={() => setActiveTab('home')}
            className="flex items-center gap-3.5 flex-1 hover:bg-sidebar-text-primary/5 transition-colors text-left group rounded-xl -ml-2 pl-2 py-1"
          >
            <div className="relative flex-shrink-0">
              <div className="absolute -inset-2 bg-accent/20 rounded-2xl blur-lg opacity-0 group-hover:opacity-100 transition duration-500" />
              <div className="relative w-11 h-11 bg-white dark:bg-slate-50 rounded-2xl flex items-center justify-center shadow-xl border border-slate-200 dark:border-accent/10 p-1.5 transition-transform group-hover:scale-105 duration-300">
                <img src="/Logo-Vinance.png" alt="Vinance Logo" className="w-full h-full object-contain" />
              </div>
            </div>
            <div className="flex flex-col">
              <span className="text-xl font-black tracking-tight text-sidebar-text-primary leading-none" style={{ textShadow: isDark ? '0 0 20px rgba(5, 150, 105, 0.4)' : 'none' }}>
                Vinance
              </span>
              <div className="flex items-center gap-1.5 mt-1">
                <span className="h-[1.5px] w-3 bg-gradient-to-r from-accent to-secondary rounded-full" />
                <span className="text-[10px] font-bold uppercase tracking-[0.25em] text-secondary/80">Ecosystem</span>
              </div>
            </div>
          </button>
          <div className="flex-shrink-0">
            {syncing ? (
              <RefreshCw className="w-3.5 h-3.5 text-accent animate-spin" />
            ) : (
              <div className={cn("w-2 h-2 rounded-full shadow-sm", isOnline ? 'bg-success shadow-success/40' : 'bg-danger shadow-danger/40')} />
            )}
          </div>
        </div>

        <div className="flex-1 overflow-y-auto no-scrollbar py-6 px-4 space-y-8">
          {/* User Section */}
          <div
            className={cn("p-3.5 rounded-[22px] bg-bg-main/40 border border-border-ui/40 flex items-center gap-3.5 cursor-pointer hover:border-accent/40 hover:bg-bg-main/60 transition-all group shadow-sm", isPending && "opacity-70")}
            onClick={() => handleTabClick('profile')}

          >
            <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-accent to-secondary p-[1.5px] flex-shrink-0 shadow-md transition-transform group-hover:rotate-3">
              <div className="w-full h-full bg-sidebar-bg rounded-[14.5px] flex items-center justify-center overflow-hidden">
                {user.photoUrl ? (
                  <img src={user.photoUrl} alt={user.name} className="w-full h-full object-cover" />
                ) : (
                  <span className="text-sm font-black text-accent">{user.name[0].toUpperCase()}</span>
                )}
              </div>
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-xs font-bold text-sidebar-text-primary truncate">{user.name}</p>
              <p className="text-[10px] text-sidebar-text-secondary/70 truncate font-medium">{user.email}</p>
            </div>
          </div>

          {/* Navigation Section */}
          <div className="space-y-1.5">
            <p className="px-4 mb-3 text-[10px] font-medium uppercase tracking-[0.2em] text-text-secondary/40">Menu Utama</p>
            <nav className="space-y-1">
              {mainTabs.map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => handleTabClick(tab.id)}
                  className={cn(
                    "w-full flex items-center gap-3.5 px-4 py-3 text-sm transition-all rounded-[18px] font-bold relative group",
                    activeTab === tab.id
                      ? "text-accent bg-accent/10 shadow-inner"
                      : "text-sidebar-text-secondary hover:text-sidebar-text-primary hover:bg-bg-main/40"
                  )}
                >
                  <tab.icon className={cn("w-4.5 h-4.5 transition-all duration-300", activeTab === tab.id ? "scale-110" : "group-hover:translate-x-0.5")} />
                  <span className="flex-1 text-left tracking-wide">{tab.label}</span>
                  {tab.id === 'transactions' && transactionBadge && (
                    <span className="flex-shrink-0 w-5 h-5 bg-gradient-to-r from-accent to-secondary text-white text-[10px] font-bold rounded-lg flex items-center justify-center shadow-lg shadow-accent/20">
                      {transactionBadge}
                    </span>
                  )}
                </button>
              ))}
            </nav>
          </div>
        </div>

        {/* Footer Section */}
        <div className="p-4 border-t border-sidebar-border/30 space-y-1">
          <button
            onClick={() => handleTabClick('profile')}
            className={cn(
              "w-full flex items-center gap-3.5 px-4 py-3 text-sm transition-all rounded-[18px] font-medium group",
              activeTab === 'profile'
                ? "text-accent bg-accent/10 shadow-inner"
                : "text-sidebar-text-secondary hover:text-sidebar-text-primary hover:bg-bg-main/40"
            )}
          >
            <User className={cn("w-4.5 h-4.5 transition-all", activeTab === 'profile' && "scale-110")} />
            <span className="tracking-wide">Profil Saya</span>
          </button>
          <button
            onClick={onLogout}
            className="w-full flex items-center gap-3.5 px-4 py-3 text-sm font-medium text-danger/80 hover:text-danger hover:bg-danger/5 transition-all rounded-[18px] group"
          >
            <div className="w-4.5 h-4.5 flex items-center justify-center transition-transform group-hover:-translate-x-0.5">
              <LogOut className="w-4.5 h-4.5" />
            </div>
            <span className="tracking-wide">Keluar Sesi</span>
          </button>
        </div>
      </aside>

      <div
        className="flex-1 flex flex-col h-screen overflow-y-auto pb-24 lg:pb-0 min-w-0 no-scrollbar sm:custom-scrollbar relative transition-colors"
      >
        {/* Wallpaper Background Layer */}
        {wallpaper !== 'none' && (
          <div className="fixed inset-0 z-0 pointer-events-none overflow-hidden">
            <div 
              className={cn(
                "absolute inset-0 transition-all duration-700",
                wallpaper === 'sunset' && "bg-gradient-to-br from-orange-400/10 to-rose-500/15",
                wallpaper === 'ocean' && "bg-gradient-to-br from-blue-600/10 to-cyan-500/15",
                wallpaper === 'forest' && "bg-gradient-to-br from-emerald-600/10 to-teal-500/15",
                wallpaper === 'royal' && "bg-gradient-to-br from-violet-600/10 to-fuchsia-500/15",
                wallpaper === 'midnight' && "bg-gradient-to-br from-slate-800/20 to-slate-900/30",
                wallpaper === 'aurora' && "bg-gradient-to-tr from-green-300/10 via-blue-500/10 to-purple-600/15",
                wallpaper === 'mesh' && "bg-[radial-gradient(at_top_left,_var(--tw-gradient-stops))] from-yellow-200/5 via-emerald-200/5 to-yellow-200/5",
                wallpaper === 'doodle' && "bg-slate-900/5 bg-[url('/doodle_wallpaper.png')] bg-repeat bg-[length:400px_400px] bg-blend-soft-light opacity-30",
                wallpaper === 'doodle2' && "bg-slate-900/5 bg-[url('/doodle_2.png')] bg-repeat bg-[length:350px_350px] bg-blend-soft-light opacity-25",
                wallpaper === 'doodle3' && "bg-[#020617]/5 bg-[url('/doodle_3.png')] bg-repeat bg-[length:500px_500px] bg-blend-soft-light opacity-20"
              )} 
              style={{
                backgroundColor: wallpaper.startsWith('#') ? `${wallpaper}15` : undefined,
                backgroundImage: wallpaper.startsWith('data:') ? `url(${wallpaper})` : undefined,
                backgroundSize: wallpaper.startsWith('data:') ? 'cover' : undefined,
                backgroundPosition: wallpaper.startsWith('data:') ? 'center' : undefined,
              }}
            />
            {/* Subtle overlay to ensure readability */}
            <div className="absolute inset-0 bg-bg-main/20 backdrop-blur-[2px]" />
          </div>
        )}

        <header className={cn(
          "bg-card-bg/80 backdrop-blur-xl border-b border-border-ui/50 px-4 sm:px-6 py-4 flex items-center justify-between z-20 sticky top-0 shadow-sm transition-all",
          isMobile && activeTab !== 'home' && "hidden"
        )}>
          <div className="relative z-10 w-full flex items-center justify-between">
            <div className="flex items-center gap-3">
              {/* Mobile: Logo & App Name */}
              <button
                onClick={() => setActiveTab('home')}
                className="flex lg:hidden items-center gap-2.5 active:scale-95 transition-transform"
              >
                <div className="w-9 h-9 bg-accent rounded-[12px] flex items-center justify-center shadow-lg p-1.5 border border-accent/20">
                  <img src="/Logo-Vinance.png" alt="Vinance Logo" className="w-full h-full object-contain brightness-0 invert" />
                </div>
                <div className="flex flex-col items-start">
                  <span className="text-lg font-black text-text-primary tracking-tight leading-none">
                    Vinance
                  </span>
                  <span className="text-[9px] text-text-secondary font-bold uppercase tracking-widest mt-1">Ecosystem</span>
                </div>
              </button>

              {/* Desktop: Active Tab Title */}
              {activeTabDef && (
                <div className="hidden lg:flex items-center gap-3">
                  <div className="w-10 h-10 rounded-[12px] bg-accent/10 flex items-center justify-center border border-accent/20 shadow-inner">
                    {React.createElement(activeTabDef.icon, { className: "w-5 h-5 text-accent" })}
                  </div>
                  <div className="flex flex-col justify-center">
                    <h1 className="text-lg font-black text-text-primary leading-none tracking-tight">{activeTabDef.label}</h1>
                    <p className="text-[10px] text-text-secondary font-bold mt-1.5 uppercase tracking-widest">
                      {activeTabDef.id === 'home' ? 'Ringkasan Keuangan' :
                        activeTabDef.id === 'transactions' ? 'Catatan Harian' :
                          activeTabDef.id === 'budgets' ? 'Manajemen Anggaran' :
                            activeTabDef.id === 'reports' ? 'Analisis Arus Kas' :
                              activeTabDef.id === 'goals' ? 'Target Tabungan' :
                                activeTabDef.id === 'notes' ? 'Memo Finansial' : 'Manajemen Akun & Sistem'}
                    </p>
                  </div>
                </div>
              )}
            </div>

            <div className="flex items-center gap-2 sm:gap-2.5">
              <motion.div
                layout
                initial={false}
                animate={{
                  width: syncing ? 'auto' : (isMobile ? '28px' : '32px'),
                  paddingLeft: syncing ? '12px' : '0px',
                  paddingRight: syncing ? '12px' : '0px'
                }}
                transition={{ type: 'spring', stiffness: 300, damping: 30 }}
                className={cn(
                  "flex items-center justify-center h-8 sm:h-9 rounded-[12px] border transition-all overflow-hidden whitespace-nowrap",
                  syncing
                    ? "bg-accent/10 border-accent/30 text-accent"
                    : isOnline
                      ? "bg-bg-main border-border-ui text-text-secondary hover:bg-border-ui"
                      : "bg-danger/10 border-danger/20 text-danger"
                )}
                title={syncing ? syncStatus : (isOnline ? 'Online & Terhubung' : 'Offline')}
              >
                <div className="flex items-center gap-2">
                  {syncing ? (
                    <RefreshCw className="w-3.5 h-3.5 sm:w-4 sm:h-4 animate-spin shrink-0" />
                  ) : isOnline ? (
                    <Cloud className="w-3.5 h-3.5 sm:w-4 sm:h-4 shrink-0" />
                  ) : (
                    <CloudOff className="w-3.5 h-3.5 sm:w-4 sm:h-4 shrink-0" />
                  )}

                  <AnimatePresence mode="wait">
                    {syncing && (
                      <motion.span
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: -10 }}
                        className="text-[9px] sm:text-[10px] font-black uppercase tracking-widest"
                      >
                        {syncStatus || 'Sinkronisasi'}
                      </motion.span>
                    )}
                  </AnimatePresence>
                </div>
              </motion.div>

              {/* Theme Toggle */}
              <button
                onClick={toggleTheme}
                className={cn(
                  "flex items-center justify-center w-8 h-8 sm:w-9 sm:h-9 rounded-[12px] transition-all border backdrop-blur-md shadow-inner",
                  isDark 
                    ? "bg-white/10 hover:bg-white/20 text-white border-white/20" 
                    : "bg-bg-main border-border-ui text-text-secondary hover:bg-border-ui"
                )}
                title={isDark ? "Mode Terang" : "Mode Gelap"}
              >
                {isDark ? <Sun className="w-4 h-4 sm:w-4.5 sm:h-4.5" /> : <Moon className="w-4 h-4 sm:w-4.5 sm:h-4.5" />}
              </button>
            </div>
          </div>
        </header>

        <main className="flex-1 p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto w-full relative z-10">
          {children}
        </main>

        {/* Mobile Menu Overlay */}
        {isMenuOpen && (
          <div className="lg:hidden">
            <div
              onClick={() => setIsMenuOpen(false)}
              className="fixed inset-0 bg-black/40 backdrop-blur-sm z-20"
            />
            <div
              className="fixed bottom-[110px] left-6 right-6 z-30"
            >
              <div className="bg-card-bg/95 backdrop-blur-xl border border-border-ui rounded-[32px] p-6 shadow-[0_12px_40px_rgba(0,0,0,0.3)]">
                <div className="flex items-center justify-between mb-6">
                  <h3 className="text-lg font-bold text-text-primary">Menu Utama</h3>
                  <button onClick={() => setIsMenuOpen(false)} className="w-8 h-8 rounded-full bg-bg-main flex items-center justify-center text-text-secondary hover:text-text-primary hover:bg-border-ui transition-all">
                    <X className="w-4.5 h-4.5" />
                  </button>
                </div>
                <div className="grid grid-cols-3 gap-y-6 gap-x-4">
                  {mainTabs.filter(tab => !['home', 'transactions'].includes(tab.id)).map((tab) => (
                    <button
                      key={tab.id}
                      onClick={() => {
                        handleTabClick(tab.id);
                        setIsMenuOpen(false);
                      }}
                      className="flex flex-col items-center gap-2.5 group"
                    >
                      <div className={cn(
                        "w-14 h-14 rounded-[20px] flex items-center justify-center transition-all duration-300 relative",
                        activeTab === tab.id
                          ? "bg-accent text-white shadow-lg shadow-accent/30 scale-105"
                          : "bg-bg-main text-text-secondary group-hover:bg-accent/10 group-hover:text-accent"
                      )}>
                        <tab.icon className="w-6 h-6" />
                        {tab.id === 'transactions' && transactionBadge && (
                          <span className="absolute -top-1.5 -right-1.5 w-5 h-5 bg-danger text-white text-[10px] font-bold rounded-full flex items-center justify-center border-2 border-card-bg shadow-sm">
                            {transactionBadge > 9 ? '9+' : transactionBadge}
                          </span>
                        )}
                      </div>
                      <span className={cn(
                        "text-[11px] font-bold text-center tracking-wide",
                        activeTab === tab.id ? "text-accent" : "text-text-secondary"
                      )}>{tab.label}</span>
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Mobile Bottom Nav Bar */}
        <div className="lg:hidden fixed bottom-0 left-0 right-0 w-full z-30 transition-all duration-500">

          {/* Background Nav with True Transparent Cutout Mask */}
          <div
            className="absolute inset-0 backdrop-blur-2xl bg-card-bg shadow-[0_-10px_40px_rgba(0,0,0,0.05)] border-t border-border-ui/50"
            style={{
              WebkitMaskImage: 'radial-gradient(circle at 50% -10px, transparent 36px, black 37px)',
              maskImage: 'radial-gradient(circle at 50% -10px, transparent 36px, black 37px)'
            }}
          />

          {/* Interactive Content Container */}
          <div className="relative px-6 py-2 flex justify-between items-center h-[65px] pb-safe">
            {/* Left Side Tabs */}
            <div className="flex justify-around flex-1 pr-6">
              <button onClick={() => handleTabClick('home')} className="flex flex-col items-center justify-center gap-1 h-full w-14 group">
                <Home className={cn("w-5 h-5 transition-colors", activeTab === 'home' ? "text-accent" : "text-text-secondary group-hover:text-text-primary")} />
                <span className={cn("text-[9px] font-bold transition-colors", activeTab === 'home' ? "text-accent" : "text-text-secondary group-hover:text-text-primary")}>Beranda</span>
              </button>
              <button onClick={() => handleTabClick('transactions')} className="flex flex-col items-center justify-center gap-1 h-full w-14 group">
                <div className="relative">
                  <List className={cn("w-5 h-5 transition-colors", activeTab === 'transactions' ? "text-accent" : "text-text-secondary group-hover:text-text-primary")} />
                  {transactionBadge && (
                    <span className="absolute -top-1 -right-1.5 w-3.5 h-3.5 bg-danger text-white text-[8px] font-bold rounded-full flex items-center justify-center border border-card-bg">
                      {transactionBadge > 9 ? '9+' : transactionBadge}
                    </span>
                  )}
                </div>
                <span className={cn("text-[9px] font-bold transition-colors", activeTab === 'transactions' ? "text-accent" : "text-text-secondary group-hover:text-text-primary")}>Riwayat</span>
              </button>
            </div>

            {/* Center: Add (+) Floating Button */}
            <div className="absolute left-1/2 -translate-x-1/2 -top-6">
              <button
                onClick={() => {
                  onAddClick();
                  setIsMenuOpen(false);
                }}
                className="w-[56px] h-[56px] rounded-full bg-gradient-to-tr from-accent to-secondary flex items-center justify-center text-white transition-transform hover:scale-105 active:scale-95 shadow-[0_8px_20px_rgba(5,150,105,0.4)]"
              >
                <Plus className="w-7 h-7" />
              </button>
            </div>

            {/* Right Side Tabs */}
            <div className="flex justify-around flex-1 pl-6">
              <button onClick={() => setIsMenuOpen(true)} className="flex flex-col items-center justify-center gap-1 h-full w-14 group">
                <LayoutGrid className={cn("w-5 h-5 transition-colors", isMenuOpen ? "text-accent" : "text-text-secondary group-hover:text-text-primary")} />
                <span className={cn("text-[9px] font-bold transition-colors", isMenuOpen ? "text-accent" : "text-text-secondary group-hover:text-text-primary")}>Menu</span>
              </button>
              <button onClick={() => handleTabClick('profile')} className="flex flex-col items-center justify-center gap-1 h-full w-14 group">
                {user.photoUrl ? (
                  <div className={cn(
                    "w-5 h-5 rounded-full overflow-hidden border transition-all",
                    activeTab === 'profile' ? "border-accent ring-1 ring-accent/30" : "border-text-secondary"
                  )}>
                    <img src={user.photoUrl} alt="Profile" className="w-full h-full object-cover" />
                  </div>
                ) : (
                  <User className={cn("w-5 h-5 transition-colors", activeTab === 'profile' ? "text-accent" : "text-text-secondary group-hover:text-text-primary")} />
                )}
                <span className={cn("text-[9px] font-bold transition-colors", activeTab === 'profile' ? "text-accent" : "text-text-secondary group-hover:text-text-primary")}>Profil</span>
              </button>
            </div>
          </div>
        </div>


      </div>
    </div>
  );
}

// src/components/Layout.vue
<template>
  <div class="h-[100dvh] bg-bg-main flex overflow-hidden relative" @click="showNotifications = false">



    <!-- ── Sidebar (Desktop Only) ── -->
    <aside class="hidden lg:flex flex-col sticky top-0 h-screen border-0 transition-all duration-500 ease-in-out z-40 bg-sidebar-bg group/sidebar overflow-hidden w-20 hover:w-64">
      <div class="px-5 py-6 border-0 flex items-center gap-4 h-[89px] shrink-0">
        <button @click="$emit('tabChange', 'home')" class="flex items-center gap-3.5 flex-1 hover:bg-sidebar-text-primary/5 transition-colors text-left group rounded-lg -ml-1 pl-1 py-1">
          <div class="relative flex-shrink-0">
            <div class="absolute -inset-2 bg-accent/20 rounded-lg blur-lg opacity-0 group-hover:opacity-100 transition duration-500" />
            <div class="relative w-10 h-10 bg-white dark:bg-slate-50 rounded-lg flex items-center justify-center shadow-xl border border-slate-200 dark:border-accent/10 p-1.5 transition-transform group-hover:scale-105 duration-300">
              <img src="/Logo-Vinance.png" alt="Vinance Logo" class="w-full h-full object-contain" />
            </div>
          </div>
          <div class="flex flex-col opacity-0 group-hover/sidebar:opacity-100 transition-opacity duration-300 whitespace-nowrap">
            <span class="text-xl font-black tracking-tight text-sidebar-text-primary leading-none">Vinance</span>
            <div class="flex items-center gap-1.5 mt-1">
              <span class="h-[1.5px] w-3 bg-gradient-to-r from-accent to-secondary rounded-full" />
              <span class="text-[10px] font-bold uppercase tracking-[0.25em] text-secondary/80">Ecosystem</span>
            </div>
          </div>
        </button>
        <div class="flex-shrink-0 opacity-0 group-hover/sidebar:opacity-100 transition-opacity duration-300">
          <RefreshCw v-if="syncing" class="w-3.5 h-3.5 text-accent animate-spin" />
          <div v-else :class="['w-2 h-2 rounded-full shadow-sm', isOnline ? 'bg-success shadow-success/40' : 'bg-danger shadow-danger/40']" />
        </div>
      </div>

      <div class="flex-1 overflow-y-auto no-scrollbar py-6 px-3.5 space-y-8">
        <div class="space-y-1.5">
          <p class="px-3.5 mb-3 text-[10px] font-medium uppercase tracking-[0.2em] text-text-secondary/40 whitespace-nowrap opacity-0 group-hover/sidebar:opacity-100 transition-opacity duration-300">{{ $t('navMenu') }}</p>
          <nav class="space-y-1">
            <button
              v-for="tab in mainTabs" :key="tab.id"
              @click="handleTabClick(tab.id)"
              :class="[
                'w-full flex items-center gap-3.5 px-3.5 py-3 text-sm transition-all rounded-lg font-bold relative group',
                activeTab === tab.id
                  ? 'text-accent bg-accent/10 shadow-inner'
                  : 'text-sidebar-text-secondary hover:text-sidebar-text-primary hover:bg-bg-main/40'
              ]"
            >
              <component :is="tab.icon" :class="['w-5 h-5 shrink-0 transition-all duration-300', activeTab === tab.id ? 'scale-110' : 'group-hover:translate-x-0.5']" />
              <span class="flex-1 text-left tracking-wide opacity-0 group-hover/sidebar:opacity-100 transition-opacity duration-300 whitespace-nowrap">{{ tab.label }}</span>
              <span v-if="tab.id === 'transactions' && transactionBadge" :class="['flex-shrink-0 w-5 h-5 bg-gradient-to-r from-accent to-secondary text-white text-[10px] font-bold rounded-lg flex items-center justify-center shadow-lg shadow-accent/20 transition-all', 'group-hover/sidebar:scale-100 scale-0 group-hover/sidebar:opacity-100 opacity-0']">{{ transactionBadge }}</span>
            </button>
          </nav>
        </div>
      </div>

      <div class="p-3.5 border-0 space-y-1 shrink-0">
        <button @click="handleTabClick('profile')" :class="['w-full flex items-center gap-3.5 px-3.5 py-3 text-sm transition-all rounded-lg font-medium group', activeTab === 'profile' ? 'text-accent bg-accent/10 shadow-inner' : 'text-sidebar-text-secondary hover:text-sidebar-text-primary hover:bg-bg-main/40']">
          <User :class="['w-5 h-5 shrink-0 transition-all', activeTab === 'profile' && 'scale-110']" />
          <span class="tracking-wide opacity-0 group-hover/sidebar:opacity-100 transition-opacity duration-300 whitespace-nowrap">{{ $t('navProfile') }}</span>
        </button>
        <button @click="$emit('logout')" class="w-full flex items-center gap-3.5 px-3.5 py-3 text-sm font-medium text-danger/80 hover:text-danger hover:bg-danger/5 transition-all rounded-lg group">
          <div class="w-5 h-5 shrink-0 flex items-center justify-center transition-transform group-hover:-translate-x-0.5">
            <LogOut class="w-5 h-5" />
          </div>
          <span class="tracking-wide opacity-0 group-hover/sidebar:opacity-100 transition-opacity duration-300 whitespace-nowrap">{{ $t('logout') }}</span>
        </button>
      </div>
    </aside>

    <!-- ── Main Content Area ── -->
    <div class="flex-1 flex flex-col h-[100dvh] overflow-y-auto pb-20 lg:pb-0 min-w-0 no-scrollbar sm:custom-scrollbar relative transition-colors">



      <!-- Desktop Header -->
      <header :class="['bg-card-bg/80 backdrop-blur-xl border-0 px-4 sm:px-6 py-4 flex items-center justify-between z-20 sticky top-0 transition-all', isMobile && 'hidden']">
        <div class="relative z-10 w-full flex items-center justify-between">
          <div class="flex items-center gap-3">
            <button @click="$emit('tabChange', 'home')" class="flex lg:hidden items-center gap-2.5 active:scale-95 transition-transform">
              <div class="w-9 h-9 bg-accent rounded-lg flex items-center justify-center shadow-lg p-1.5 border border-accent/20">
                <img src="/Logo-Vinance.png" alt="Vinance Logo" class="w-full h-full object-contain brightness-0 invert" />
              </div>
              <div class="flex flex-col items-start">
                <span class="text-lg font-black text-text-primary tracking-tight leading-none">Vinance</span>
                <span class="text-[9px] text-text-secondary font-bold uppercase tracking-widest mt-1">Ecosystem</span>
              </div>
            </button>

            <div v-if="activeTabDef" class="hidden lg:flex items-center gap-3">
              <div class="w-10 h-10 rounded-md bg-accent/10 flex items-center justify-center border border-accent/20 shadow-inner">
                <component :is="activeTabDef.icon" class="w-5 h-5 text-accent" />
              </div>
              <div class="flex flex-col justify-center">
                <h1 class="text-lg font-black text-text-primary leading-none tracking-tight">{{ activeTabDef.label }}</h1>
                <p class="text-[10px] text-text-secondary font-bold mt-1.5 uppercase tracking-widest">{{ tabSubtitle }}</p>
              </div>
            </div>
          </div>

          <div class="flex items-center gap-2 sm:gap-2.5 relative">
            <!-- Online/Sync Status -->
            <div class="relative">
              <button
                @click.stop="showNotifications = !showNotifications"
                :class="[
                  'flex items-center justify-center h-8 sm:h-10 px-3 sm:px-4 rounded-lg border transition-all duration-300 relative group overflow-hidden shadow-sm',
                  syncing ? 'bg-accent/10 border-accent/30 text-accent'
                    : isOnline ? 'bg-accent/5 border-accent/25 text-accent hover:border-accent/40 hover:bg-accent/10'
                    : 'bg-danger/10 border-danger/20 text-danger',
                  showNotifications && 'ring-2 ring-accent/30 border-accent/50 bg-accent/5'
                ]"
              >
                <div class="flex items-center gap-2.5 relative z-10">
                  <RefreshCw v-if="syncing" class="w-4 h-4 animate-spin shrink-0" />
                  <div v-else-if="isOnline" class="relative">
                    <Cloud class="w-4 h-4 shrink-0 transition-transform group-hover:scale-110 duration-300" />
                    <div class="absolute -top-1 -right-1 w-2 h-2 bg-success rounded-full border-2 border-white dark:border-slate-800 shadow-[0_0_8px_rgba(34,197,94,0.6)] animate-pulse" />
                  </div>
                  <div v-else class="relative">
                    <CloudOff class="w-4 h-4 shrink-0" />
                    <div class="absolute -top-1 -right-1 w-2 h-2 bg-danger rounded-full border-2 border-white dark:border-slate-800" />
                  </div>
                  <div class="flex flex-col items-start leading-none hidden sm:flex">
                    <span class="text-[10px] font-black uppercase tracking-widest">{{ syncing ? 'Sinkronisasi' : isOnline ? 'Online' : 'Offline' }}</span>
                  </div>
                  <div v-if="notificationCount > 0" class="w-4 h-4 bg-accent text-white text-[9px] font-black rounded-lg flex items-center justify-center shadow-lg shadow-accent/20">{{ notificationCount }}</div>
                </div>
              </button>

              <!-- Notifications Dropdown -->
              <div v-if="showNotifications" @click.stop class="absolute right-0 mt-3 w-80 bg-card-bg/95 backdrop-blur-2xl border border-border-ui rounded-lg shadow-[0_20px_50px_-12px_rgba(0,0,0,0.5)] overflow-hidden z-50 p-4">
                <div class="flex items-center justify-between mb-4 px-2">
                  <h4 class="text-xs font-black text-text-primary uppercase tracking-widest">Pemberitahuan</h4>
                  <span v-if="notificationCount > 0" class="text-[10px] font-bold text-accent bg-accent/10 px-2 py-0.5 rounded-full">{{ notificationCount }} Baru</span>
                </div>
                <div class="space-y-3 max-h-[400px] overflow-y-auto no-scrollbar py-1">
                  <div v-if="notificationCount === 0" class="flex flex-col items-center justify-center py-10 text-text-secondary/40">
                    <Bell class="w-8 h-8 mb-2 stroke-[1.5]" />
                    <p class="text-[10px] font-bold uppercase tracking-widest">Tidak ada notifikasi</p>
                  </div>
                  <template v-else>
                    <div v-for="toast in toasts" :key="toast.id" :class="['p-3 rounded-lg flex items-center gap-3 border transition-colors', toastClass(toast.type)]">
                      <div class="shrink-0">
                        <CheckCircle2 v-if="toast.type === 'success'" class="w-4 h-4" />
                        <AlertOctagon v-else-if="toast.type === 'error'" class="w-4 h-4" />
                        <AlertTriangle v-else-if="toast.type === 'warning'" class="w-4 h-4" />
                        <Info v-else class="w-4 h-4" />
                      </div>
                      <p class="text-[11px] font-bold leading-tight flex-1">{{ toast.message }}</p>
                    </div>
                  </template>
                </div>
              </div>
            </div>

            <!-- Theme toggle -->
            <button @click="$emit('toggleTheme')" :class="['flex items-center justify-center w-8 h-8 sm:w-9 sm:h-9 rounded-md transition-all border backdrop-blur-md shadow-inner', isDark ? 'bg-white/10 hover:bg-white/20 text-white border-white/20' : 'bg-bg-main border-border-ui text-text-secondary hover:bg-border-ui']">
              <Sun v-if="isDark" class="w-4 h-4" />
              <Moon v-else class="w-4 h-4" />
            </button>
          </div>
        </div>
      </header>

      <!-- Main slot content -->
      <main :class="['flex-1 max-w-[1600px] mx-auto w-full relative z-10', isMobile ? 'p-0' : 'p-5']">
        <template v-if="isMobile && activeTab !== 'home'">
          <div>
            <!-- ══ Mobile Page Header ══ -->
            <div
              class="relative pt-4 pb-12 px-5 text-white overflow-hidden"
              style="background: linear-gradient(160deg, #0f1f4b 0%, #1A2C5B 45%, #1e3a8a 100%)"
            >
              <div class="absolute top-0 right-0 w-56 h-56 bg-blue-400/8 rounded-full blur-3xl pointer-events-none" />
              <div class="absolute -bottom-12 -left-10 w-44 h-44 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />

              <div class="relative z-10">
                <div class="flex items-center justify-between">
                  <!-- Page title + icon pill -->
                  <div class="flex items-center gap-3">
                    <div v-if="activeTabDef" class="w-9 h-9 rounded-xl bg-white/12 border border-white/15 flex items-center justify-center">
                      <component :is="activeTabDef.icon" class="w-4.5 h-4.5 text-white/90" />
                    </div>
                    <div>
                      <p class="text-[20px] font-black text-white tracking-tight leading-none">{{ activeTabDef?.label || 'Vinance' }}</p>
                      <p class="text-[9.5px] font-semibold text-white/45 uppercase tracking-[0.2em] mt-1">{{ mobileTabSubtitle }}</p>
                    </div>
                  </div>

                  <!-- Controls -->
                  <div class="flex items-center gap-2">
                    <button v-if="activeTabDef?.id !== 'profile'" @click="$emit('toggleTheme')" class="w-9 h-9 flex items-center justify-center rounded-full bg-white/10 active:scale-90 transition-all">
                      <Sun v-if="isDark" class="w-4 h-4 text-amber-300" />
                      <Moon v-else class="w-4 h-4 text-white/80" />
                    </button>
                    <button @click.stop="showNotifications = !showNotifications" class="w-9 h-9 flex items-center justify-center rounded-full bg-white/10 active:scale-90 transition-all relative">
                      <Bell class="w-4 h-4 text-white/80" />
                      <span v-if="notificationCount > 0" class="absolute top-2 right-2 w-2 h-2 bg-rose-400 rounded-full border-0 animate-pulse" />
                    </button>
                    <button v-if="activeTabDef?.id !== 'profile'" @click="handleTabClick('profile')" class="w-10 h-10 rounded-full active:scale-90 transition-all focus:outline-none ring-2 ring-white/20">
                      <img v-if="user?.photoUrl" :src="user.photoUrl" alt="profil" class="w-10 h-10 rounded-full object-cover" />
                      <div v-else class="w-10 h-10 rounded-full bg-gradient-to-br from-blue-400/40 to-indigo-500/40 border-0 flex items-center justify-center">
                        <span class="text-white font-black text-sm">{{ user?.name ? user.name[0].toUpperCase() : 'U' }}</span>
                      </div>
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <!-- ══ Content Sheet ══ -->
            <div class="bg-bg-main rounded-t-[10px] mt-[-28px] relative z-10 px-4 pt-6 pb-28 min-h-[calc(100dvh-120px)]">
              <slot />
            </div>
          </div>
        </template>
        <template v-else>
          <slot />
        </template>
      </main>

      <!-- Mobile Bottom Nav — 5 Tab Native Style -->
      <div class="lg:hidden fixed bottom-0 left-0 right-0 w-full h-[90px] z-30 pointer-events-none">
        <!-- Glassmorphic background with center cutout -->
        <div
          class="absolute bottom-0 left-0 right-0 h-[62px] backdrop-blur-2xl bg-card-bg/96 border-0"
          :style="{
            WebkitMaskImage: 'radial-gradient(ellipse 60px 32px at 50% 0%, transparent 96%, black 100%)',
            maskImage: 'radial-gradient(ellipse 60px 32px at 50% 0%, transparent 96%, black 100%)'
          }"
        />

        <!-- Floating Center Add Button -->
        <div class="absolute left-1/2 -translate-x-1/2 top-0 z-20 pointer-events-auto">
          <button
            @click="$emit('addClick')"
            class="w-[56px] h-[56px] rounded-full flex items-center justify-center text-white active:scale-90 hover:scale-105 transition-all duration-200 shadow-[0_6px_24px_rgba(26,44,91,0.55)]"
            style="background: linear-gradient(145deg, #2D4DB5 0%, #1A2C5B 100%)"
          >
            <Plus class="w-6 h-6 stroke-[2.5]" />
          </button>
        </div>

        <!-- Nav Tab Items -->
        <div class="absolute bottom-0 left-0 right-0 flex items-stretch justify-around px-1 h-[62px] pointer-events-auto z-10">

          <!-- Beranda -->
          <button @click="handleTabClick('home')" class="flex flex-col items-center justify-center gap-[3px] flex-1 h-full pt-1.5 relative">
            <div :class="['absolute top-0 left-1/2 -translate-x-1/2 h-[3px] rounded-b-full transition-all duration-300', activeTab === 'home' ? 'w-8 bg-accent' : 'w-0 bg-transparent']" />
            <Home :class="['transition-all duration-300', activeTab === 'home' ? 'w-[22px] h-[22px] text-accent' : 'w-[20px] h-[20px] text-text-secondary/50']" />
            <span :class="['text-[9.5px] font-black tracking-tight transition-colors leading-none', activeTab === 'home' ? 'text-accent' : 'text-text-secondary/50']">Beranda</span>
          </button>

          <!-- Transaksi -->
          <button @click="handleTabClick('transactions')" class="flex flex-col items-center justify-center gap-[3px] flex-1 h-full pt-1.5 relative">
            <div :class="['absolute top-0 left-1/2 -translate-x-1/2 h-[3px] rounded-b-full transition-all duration-300', activeTab === 'transactions' ? 'w-8 bg-accent' : 'w-0 bg-transparent']" />
            <List :class="['transition-all duration-300', activeTab === 'transactions' ? 'w-[22px] h-[22px] text-accent' : 'w-[20px] h-[20px] text-text-secondary/50']" />
            <span :class="['text-[9.5px] font-black tracking-tight transition-colors leading-none', activeTab === 'transactions' ? 'text-accent' : 'text-text-secondary/50']">Transaksi</span>
          </button>

          <!-- Spacer for floating button -->
          <div class="flex-1 pointer-events-none" />

          <!-- Laporan -->
          <button @click="handleTabClick('reports')" class="flex flex-col items-center justify-center gap-[3px] flex-1 h-full pt-1.5 relative">
            <div :class="['absolute top-0 left-1/2 -translate-x-1/2 h-[3px] rounded-b-full transition-all duration-300', activeTab === 'reports' ? 'w-8 bg-accent' : 'w-0 bg-transparent']" />
            <PieChart :class="['transition-all duration-300', activeTab === 'reports' ? 'w-[22px] h-[22px] text-accent' : 'w-[20px] h-[20px] text-text-secondary/50']" />
            <span :class="['text-[9.5px] font-black tracking-tight transition-colors leading-none', activeTab === 'reports' ? 'text-accent' : 'text-text-secondary/50']">Laporan</span>
          </button>

          <!-- Lainnya (Menu + all others) -->
          <button @click="handleTabClick('menu')" class="flex flex-col items-center justify-center gap-[3px] flex-1 h-full pt-1.5 relative">
            <div :class="['absolute top-0 left-1/2 -translate-x-1/2 h-[3px] rounded-b-full transition-all duration-300', ['menu','profile','budgets','goals','notes'].includes(activeTab) ? 'w-8 bg-accent' : 'w-0 bg-transparent']" />
            <LayoutGrid :class="['transition-all duration-300', ['menu','profile','budgets','goals','notes'].includes(activeTab) ? 'w-[22px] h-[22px] text-accent' : 'w-[20px] h-[20px] text-text-secondary/50']" />
            <span :class="['text-[9.5px] font-black tracking-tight transition-colors leading-none', ['menu','profile','budgets','goals','notes'].includes(activeTab) ? 'text-accent' : 'text-text-secondary/50']">Lainnya</span>
          </button>

        </div>
      </div>
    </div>

    <!-- Global Toast Container -->
    <Teleport to="body">
      <div class="fixed top-4 left-1/2 -translate-x-1/2 z-[10000] flex flex-col items-center gap-2 pointer-events-none w-full max-w-sm px-4">
        <TransitionGroup name="toast">
          <div
            v-for="toast in toasts" :key="toast.id"
            :class="['p-3 rounded-xl flex items-center gap-3 border shadow-xl backdrop-blur-xl pointer-events-auto w-full', toastSolidClass(toast.type)]"
          >
            <div class="shrink-0 bg-white/20 p-1.5 rounded-lg">
              <CheckCircle2 v-if="toast.type === 'success'" class="w-4 h-4" />
              <AlertOctagon v-else-if="toast.type === 'error'" class="w-4 h-4" />
              <AlertTriangle v-else-if="toast.type === 'warning'" class="w-4 h-4" />
              <Info v-else class="w-4 h-4" />
            </div>
            <p class="text-xs font-bold leading-tight flex-1">{{ toast.message }}</p>
          </div>
        </TransitionGroup>
      </div>
    </Teleport>

    <!-- Global Dialog Modal -->
    <Teleport to="body">
      <div v-if="activeDialog" class="fixed inset-0 z-[10000] flex items-center justify-center p-4">
        <div class="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" />
        <div class="relative w-full max-w-sm bg-card-bg rounded-2xl shadow-2xl border border-border-ui p-6">
          <div class="flex flex-col items-center text-center space-y-4">
            <div class="w-16 h-16 rounded-2xl bg-accent/10 text-accent flex items-center justify-center border border-accent/20">
              <AlertCircle v-if="activeDialog.type === 'confirm'" class="w-8 h-8" />
              <Info v-else class="w-8 h-8" />
            </div>
            <div>
              <h3 class="text-xl font-black text-text-primary tracking-tight">{{ activeDialog.title }}</h3>
              <p class="text-sm text-text-secondary mt-2 leading-relaxed">{{ activeDialog.message }}</p>
            </div>
            <div class="flex gap-3 w-full pt-4">
              <button v-if="activeDialog.type === 'confirm'" @click="activeDialog.onCancel()" class="flex-1 py-3.5 bg-bg-main text-text-secondary rounded-xl text-xs font-bold border border-border-ui hover:bg-border-ui transition-colors">
                {{ (activeDialog.cancelText || 'Batal').toUpperCase() }}
              </button>
              <button @click="activeDialog.onConfirm()" class="flex-1 py-3.5 bg-accent text-white rounded-xl text-xs font-black shadow-lg shadow-accent/25 hover:shadow-accent/40 active:scale-95 transition-all">
                {{ (activeDialog.confirmText || 'Oke').toUpperCase() }}
              </button>
            </div>
          </div>
        </div>
      </div>
    </Teleport>

    <!-- Mobile Notification Panel -->
    <Teleport to="body">
      <div v-if="isMobile && showNotifications" class="fixed inset-0 z-[10000] bg-bg-main flex flex-col overflow-hidden" @click.stop>
        <div
          class="relative pt-4 pb-12 px-5 text-white overflow-hidden shrink-0"
          style="background: linear-gradient(160deg, #0f1f4b 0%, #1A2C5B 45%, #1e3a8a 100%)"
        >
          <div class="absolute top-0 right-0 w-56 h-56 bg-blue-400/8 rounded-full blur-3xl pointer-events-none" />
          <div class="absolute -bottom-12 -left-10 w-44 h-44 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />
          <div class="relative z-10">
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-3">
                <button @click="showNotifications = false" class="w-9 h-9 flex items-center justify-center rounded-full bg-white/10 border border-white/15 active:scale-90 transition-all">
                  <ArrowLeft class="w-5 h-5 stroke-[2.5] text-white" />
                </button>
                <div>
                  <h1 class="text-[20px] font-black text-white tracking-tight leading-none">{{ $t('notifications') }}</h1>
                  <p class="text-[9.5px] font-semibold text-white/45 uppercase tracking-[0.2em] mt-1">Informasi &amp; Aktivitas</p>
                </div>
              </div>
              <span v-if="notificationCount > 0" class="text-[10px] font-bold text-emerald-400 bg-emerald-500/15 px-3 py-1 rounded-full border border-emerald-500/25">{{ notificationCount }} Baru</span>
            </div>
          </div>
        </div>
        <div class="flex-1 bg-bg-main rounded-t-[10px] mt-[-28px] relative z-10 px-5 pt-8 pb-12 overflow-y-auto no-scrollbar">
          <div class="space-y-4 max-w-lg mx-auto">
            <div v-if="notificationCount === 0" class="flex flex-col items-center justify-center py-28 text-text-secondary/30">
              <div class="w-16 h-16 rounded-full bg-accent/5 flex items-center justify-center border border-accent/10 mb-4 animate-pulse">
                <Bell class="w-8 h-8 text-accent/60 stroke-[1.5]" />
              </div>
              <p class="text-xs font-bold uppercase tracking-widest text-center">{{ $t('noNotifications') }}</p>
            </div>
            <template v-else>
              <div v-for="toast in toasts" :key="toast.id" :class="['p-4 rounded-2xl flex items-start gap-3.5 border-0 transition-colors', toastClass(toast.type)]">
                <div class="w-8 h-8 rounded-xl bg-current/10 flex items-center justify-center shrink-0 border-0">
                  <CheckCircle2 v-if="toast.type === 'success'" class="w-5 h-5" />
                  <AlertOctagon v-else-if="toast.type === 'error'" class="w-5 h-5" />
                  <AlertTriangle v-else-if="toast.type === 'warning'" class="w-5 h-5" />
                  <Info v-else class="w-5 h-5" />
                </div>
                <p class="text-xs font-bold leading-normal flex-1 mt-1">{{ toast.message }}</p>
              </div>
            </template>
          </div>
        </div>
      </div>
    </Teleport>

  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import { isToday } from 'date-fns';
import { useI18n } from 'vue-i18n';
import {
  Home, List, PieChart, Target, User, LogOut, Moon, Sun, Plus, RefreshCw,
  StickyNote, Flag, Cloud, CloudOff, LayoutGrid, Bell,
  AlertCircle, CheckCircle2, AlertOctagon, AlertTriangle, Info, ArrowLeft
} from '@lucide/vue';
import type { Transaction, Budget, User as UserType } from '../types';

interface Props {
  activeTab: string;
  user: UserType;
  isDark: boolean;
  transactions: Transaction[];
  budgets: Budget[];
  syncing: boolean;
  toasts?: any[];
  activeDialog?: any;
}

const props = withDefaults(defineProps<Props>(), {
  toasts: () => [],
  activeDialog: null,
});

const emit = defineEmits<{
  tabChange: [tab: string];
  toggleTheme: [];
  logout: [];
  addClick: [];
}>();

const isOnline = ref(navigator.onLine);
const showNotifications = ref(false);
const isMobile = ref(typeof window !== 'undefined' ? window.innerWidth < 1024 : false);

const { t } = useI18n();

const mainTabs = computed(() => [
  { id: 'home', icon: Home, label: t('navHome') },
  { id: 'transactions', icon: List, label: t('navTransactions') },
  { id: 'budgets', icon: Target, label: t('navBudgets') },
  { id: 'reports', icon: PieChart, label: t('navReports') },
  { id: 'goals', icon: Flag, label: t('navGoals') },
  { id: 'notes', icon: StickyNote, label: t('navNotes') },
]);
const allTabs = computed(() => [...mainTabs.value, { id: 'profile', icon: User, label: t('navProfile') }, { id: 'menu', icon: LayoutGrid, label: t('navMenu') }]);

const transactionBadge = computed(() => {
  const count = (props.transactions || []).filter(t => isToday(new Date(t.date))).length;
  return count > 0 ? count : null;
});

const activeTabDef = computed(() => allTabs.value.find(t => t.id === props.activeTab));

const notificationCount = computed(() => (props.toasts?.length || 0) + (props.activeDialog ? 1 : 0));

const tabSubtitle = computed(() => {
  const id = props.activeTab;
  return id === 'home' ? t('subHome')
    : id === 'transactions' ? t('subTransactions')
    : id === 'budgets' ? t('subBudgets')
    : id === 'reports' ? t('subReports')
    : id === 'goals' ? t('subGoals')
    : id === 'notes' ? t('subNotes')
    : t('subProfile');
});

const mobileTabSubtitle = computed(() => {
  const id = activeTabDef.value?.id;
  return id === 'transactions' ? t('subTransactions')
    : id === 'budgets' ? t('subBudgets')
    : id === 'reports' ? t('subReports')
    : id === 'goals' ? t('subGoals')
    : id === 'notes' ? t('subNotes')
    : id === 'menu' ? t('navMenu')
    : t('subProfile');
});



const toastClass = (type: string) => {
  if (type === 'success') return 'bg-success/5 border-0 text-success';
  if (type === 'error') return 'bg-danger/5 border-0 text-danger';
  if (type === 'warning') return 'bg-warning/5 border-0 text-warning';
  return 'bg-accent/5 border-0 text-accent';
};

const toastSolidClass = (type: string) => {
  if (type === 'success') return 'bg-success/90 border-0 text-white';
  if (type === 'error') return 'bg-danger/90 border-0 text-white';
  if (type === 'warning') return 'bg-warning/90 border-0 text-white';
  return 'bg-accent/90 border-0 text-white';
};

const handleTabClick = (tabId: string) => {
  if (props.activeTab === tabId) return;
  emit('tabChange', tabId);
};

const handleOnline = () => { isOnline.value = true; };
const handleOffline = () => { isOnline.value = false; };
const handleResize = () => { isMobile.value = window.innerWidth < 1024; };

onMounted(() => {
  window.addEventListener('online', handleOnline);
  window.addEventListener('offline', handleOffline);
  window.addEventListener('resize', handleResize);
});

onUnmounted(() => {
  window.removeEventListener('online', handleOnline);
  window.removeEventListener('offline', handleOffline);
  window.removeEventListener('resize', handleResize);
});
</script>

<style scoped>
.toast-enter-active, .toast-leave-active { transition: all 0.3s ease; }
.toast-enter-from { opacity: 0; transform: translateY(-12px); }
.toast-leave-to { opacity: 0; transform: translateY(-12px); }
</style>
